# Generated by Django 3.0.2 on 2020-02-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20191220_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='cam',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='mic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='faq',
            name='example',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='ztruser',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ztruser',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ztruser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
