# Generated by Django 3.0.2 on 2020-02-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20200201_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ztruser',
            name='user_devices',
            field=models.ManyToManyField(blank=True, to='base_app.Devices'),
        ),
        migrations.AlterField(
            model_name='ztruser',
            name='user_products',
            field=models.ManyToManyField(blank=True, to='base_app.Product'),
        ),
    ]
